In [35]:
import os
import pandas as pd
import numpy as np
import re
from pathlib import Path

initialDB_path = Path('../data/initialDB_sequences.csv')
initialDB = pd.read_csv(initialDB_path, sep=',', header=0, comment='#', names=[
    'gene_id', 'transcript_id', "5' UTR", 'start_codon', 'CDS', 'stop_codon', "3' UTR", 'appris_rank', "5' UTR_len", 'CDS_len', "3' UTR_len"
])

df = initialDB.copy()
df.head()

,gene_id,transcript_id,5' UTR,start_codon,CDS,stop_codon,3' UTR,appris_rank,5' UTR_len,CDS_len,3' UTR_len
0,ENSG00000186092.7,ENST00000641515.2,CCCAGATCTCTTCAGTTTTTATGCCTCATTCTGTGAAAATTGCTGT...,ATG,ATGAAGAAGGTAACTGCAGAGGCTATTTCCTGGAATGAATCAACGA...,TAG,NaN,1,60,981,0
1,ENSG00000284733.2,ENST00000426406.4,NaN,ATG,ATGGATGGAGAGAATCACTCAGTGGTATCTGAGTTTTTGTTTCTGG...,TAA,TAA,1,0,939,3
2,ENSG00000284662.2,ENST00000332831.5,NaN,ATG,ATGGATGGAGAGAATCACTCAGTGGTATCTGAGTTTTTGTTTCTGG...,TAA,TAA,1,0,939,3
3,ENSG00000187634.14,ENST00000616016.5,GGCGGCGGAGTCTCCCAAGTCCCCGCCGGGCGGGCGCGCGCCAGTG...,ATG,ATGCCGGCGGTCAAGAAGGAGTTCCCGGGCCGCGAGGACCTGGCCC...,TGA,NaN,10,509,2535,0
4,ENSG00000188976.12,ENST00000327044.7,GCTTCGGGTTGGTGTC,ATG,ATGGCAGCTGCGGGGAGCCGCAAGAGGCGCCTGGCGGAGCTGACGG...,TGA,TGAGGCAGCCCATCTGGGGGGCCTGTAGGGGCTGCCGGGCTGGTGG...,3,16,2250,494

In [36]:
df.drop(columns=['gene_id', "5' UTR_len", 'CDS_len', "3' UTR_len"], inplace=True)

df.head()

,transcript_id,5' UTR,start_codon,CDS,stop_codon,3' UTR,appris_rank
0,ENST00000641515.2,CCCAGATCTCTTCAGTTTTTATGCCTCATTCTGTGAAAATTGCTGT...,ATG,ATGAAGAAGGTAACTGCAGAGGCTATTTCCTGGAATGAATCAACGA...,TAG,NaN,1
1,ENST00000426406.4,NaN,ATG,ATGGATGGAGAGAATCACTCAGTGGTATCTGAGTTTTTGTTTCTGG...,TAA,TAA,1
2,ENST00000332831.5,NaN,ATG,ATGGATGGAGAGAATCACTCAGTGGTATCTGAGTTTTTGTTTCTGG...,TAA,TAA,1
3,ENST00000616016.5,GGCGGCGGAGTCTCCCAAGTCCCCGCCGGGCGGGCGCGCGCCAGTG...,ATG,ATGCCGGCGGTCAAGAAGGAGTTCCCGGGCCGCGAGGACCTGGCCC...,TGA,NaN,10
4,ENST00000327044.7,GCTTCGGGTTGGTGTC,ATG,ATGGCAGCTGCGGGGAGCCGCAAGAGGCGCCTGGCGGAGCTGACGG...,TGA,TGAGGCAGCCCATCTGGGGGGCCTGTAGGGGCTGCCGGGCTGGTGG...,3

In [37]:
df = initialDB.copy()
df['sequence'] = (
    df["5' UTR"].fillna('').astype(str)
    + df['CDS'].fillna('').astype(str)
    + df["3' UTR"].fillna('').astype(str)
)
df.drop(columns=['gene_id', '5\' UTR', 'CDS', '3\' UTR', 'start_codon', 'stop_codon', 'appris_rank', '5\' UTR_len', 'CDS_len', '3\' UTR_len'], inplace=True)
df.rename(columns={'transcript_id': 'id'}, inplace=True)

df.head()

                  id                                           sequence
0  ENST00000641515.2  CCCAGATCTCTTCAGTTTTTATGCCTCATTCTGTGAAAATTGCTGT...
1  ENST00000426406.4  ATGGATGGAGAGAATCACTCAGTGGTATCTGAGTTTTTGTTTCTGG...
2  ENST00000332831.5  ATGGATGGAGAGAATCACTCAGTGGTATCTGAGTTTTTGTTTCTGG...
3  ENST00000616016.5  GGCGGCGGAGTCTCCCAAGTCCCCGCCGGGCGGGCGCGCGCCAGTG...
4  ENST00000327044.7  GCTTCGGGTTGGTGTCATGGCAGCTGCGGGGAGCCGCAAGAGGCGC...

In [38]:
df.to_csv('../data/ARMnet_sequences.csv', index=False)