In [7]:
import pandas as pd
from pathlib import Path

tcell_path = Path('../data/tcell_specific_genes.csv')
initialDB_path = Path('../data/initialDB_sequences.csv')

df = pd.read_csv(tcell_path)
initialDB_df = pd.read_csv(initialDB_path)

In [ ]:
initialDB_lookup = initialDB_df.assign(gene_id=initialDB_df['gene_id'].str.split('.').str[0]).set_index('gene_id')

df["5' UTR"] = df['ensembl_id'].map(initialDB_lookup["5' UTR"])
df['CDS'] = df['ensembl_id'].map(initialDB_lookup['CDS'])
df["3' UTR"] = df['ensembl_id'].map(initialDB_lookup["3' UTR"])

df

,rank,ensembl_id,gene_symbol,whole_blood_tpm,spleen_tpm,ebv_bcell_tpm,tcell_rich_mean_tpm,tcell_score,max_tpm,max_tissue,5' UTR,CDS,3' UTR
0,1,ENSG00000188404,SELL,1988.320000,203.77800,94.702300,1096.049000,1001.346700,1988.3200,Whole_Blood,GACATTCAGTGCAGTCTACCTGCAGCACAGCACACTCCCTTTGGGC...,ATGATATTTCCATGGAAATGTCAGAGCACCCAGAGGGACTTATGGA...,TAAATCGCCCTTGGTGAAAGAAAATTCTTGGAATACTAAAAATCAT...
1,2,ENSG00000105374,NKG7,851.196000,196.77200,8.873410,523.984000,515.110590,851.1960,Whole_Blood,CTTTCTTGGGCTCTAAGGACCCAGGAGTCTGGGTGCACAGCCTCCT...,ATGGAGCTCTGCCGGTCCCTGGCCCTGCTGGGGGGCTCCCTGGGCC...,TGAGCAGAAGGCAAGAGCGGCAAGATGAGTTTTGAGCGTTGTATTC...
2,3,ENSG00000121966,CXCR4,562.914000,363.96300,32.538800,463.438500,430.899700,1192.1300,Small_Intestine_Terminal_Ileum_Lymphoid_Aggregate,AGTTTGTTGGCTGCGGCAGCAGGTAGCAAAGTGACGCCGAGGGCCT...,ATGGAGGGGATCAGTATATACACTTCAGATAACTACACCGAGGAAA...,TAACACAGATGTAAAAGACTTTTTTTTATACGATAAATAACTTTTT...
3,4,ENSG00000113916,BCL6,500.122000,194.59700,0.536033,347.359500,346.823467,500.1220,Whole_Blood,AGAACTGGGGTTCTTAGAAGTGGTGATGCAAGAAGTTTCTAGGAAA...,ATGGCCTCGCCGGCTGACAGCTGTATCCAGTTCACCCGCCATGCCA...,TGAAGCATGGAGTGTTGATGCTTTCGTCTCCAGCCCCTTCTCAGAA...
4,5,ENSG00000211772,TRBC2,292.210000,261.98300,91.725100,277.096500,185.371400,648.8620,Small_Intestine_Terminal_Ileum_Lymphoid_Aggregate,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,73,ENSG00000188389,PDCD1,4.550410,13.10960,21.919600,8.830005,0.000000,27.6474,Small_Intestine_Terminal_Ileum_Lymphoid_Aggregate,GCTCACCTCCGCCTGAGCAGTGGAGAAGGCGGCACTCTGGTGGGGC...,ATGCAGATCCCACAGGCGCCCTGGCCAGTCGTCTGGGCGGTGCTAC...,TGACCGGCTTCCTTGGCCACCAGTGTTCTGCAGACCCTCCACCATG...
73,74,ENSG00000030419,IKZF2,0.675437,2.69303,82.107700,1.684233,0.000000,82.1077,Cells_EBV-transformed_lymphocytes,GCTAACCCTGCTCCTCGCTGAAGATGGAGGAAGTAAAAACAGGATT...,ATGGAAACAGAGGCTATTGATGGCTATATAACGTGTGACAATGAGC...,TAGGCCTTTTCATTCCAAAGGGGACCCCTATGAAGTAAAGAACTGC...
74,75,ENSG00000182866,LCK,71.600200,60.29520,109.453000,65.947700,0.000000,132.6870,Small_Intestine_Terminal_Ileum_Lymphoid_Aggregate,GAGACAGGTGGTGGCTACGACGGCGAAGGGAGCTGAGACTGTCCAG...,ATGGGCTGTGGCTGCAGCTCACACCCGGAAGATGACTGGATGGAAA...,NaN
75,76,ENSG00000020633,RUNX3,46.372000,54.99760,151.434000,50.684800,0.000000,151.4340,Cells_EBV-transformed_lymphocytes,GCCACTTGATTCTGGAGGATTTGTTCTGGGGCTGCGGCCGCGGAGT...,ATGCGTATTCCCGTAGACCCAAGCACCAGCCGCCGCTTCACACCTC...,TGACCGCCCTGGTGGACTCCTCCCGCTGGAGGCGGGGACCCTAACA...
76,77,ENSG00000186810,CXCR3,4.238650,12.08610,20.415800,8.162375,0.000000,20.4158,Cells_EBV-transformed_lymphocytes,ACAAGCACCAAAGCAGAGGGGCAGGCAGCACACCACCCAGCAGCCA...,ATGGTCCTTGAGGTGAGTGACCACCAAGTGCTAAATGACGCCGAGG...,TGAGGCCGGAATCCGGGCTCCCCTTTCGCCCACAGTCTGACTTCCC...

In [17]:
to_check = df[df["5' UTR"].isna() | df['CDS'].isna().isna()]
to_check

,rank,ensembl_id,gene_symbol,whole_blood_tpm,spleen_tpm,ebv_bcell_tpm,tcell_rich_mean_tpm,tcell_score,max_tpm,max_tissue,5' UTR,CDS,3' UTR
4,5,ENSG00000211772,TRBC2,292.21000,261.98300,91.725100,277.096500,185.371400,648.86200,Small_Intestine_Terminal_Ileum_Lymphoid_Aggregate,NaN,NaN,NaN
6,7,ENSG00000211751,TRBC1,172.61500,119.51200,1.724980,146.063500,144.338520,267.05600,Small_Intestine_Terminal_Ileum_Lymphoid_Aggregate,NaN,NaN,NaN
20,21,ENSG00000211829,TRDC,36.92840,38.18550,1.636830,37.556950,35.920120,38.18550,Spleen,NaN,NaN,NaN
24,25,ENSG00000227191,TRGC2,26.15780,34.23340,0.062568,30.195600,30.133032,34.23340,Spleen,NaN,NaN,NaN
46,47,ENSG00000256553,TRAV1-2,3.11677,3.12613,0.000000,3.121450,3.121450,3.60373,Liver_Portal_Tract,NaN,NaN,NaN
52,53,ENSG00000211689,TRGC1,1.51318,1.88683,0.000000,1.700005,1.700005,12.57210,Prostate,NaN,NaN,NaN
60,61,ENSG00000277734,TRAC,194.21200,170.65200,240.271000,182.432000,0.000000,387.02300,Small_Intestine_Terminal_Ileum_Lymphoid_Aggregate,NaN,NaN,NaN